/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Player = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Nat,
  'joinedAt' : IDL.Nat,
  'isHost' : IDL.Bool,
  'roomId' : IDL.Nat,
});
export const GameStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : GameStatus,
  'endTime' : IDL.Opt(IDL.Int),
  'roomId' : IDL.Nat,
});
export const RoomStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
  'InProgress' : IDL.Null,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'status' : RoomStatus,
  'code' : IDL.Text,
  'adminToken' : IDL.Text,
  'hostId' : IDL.Nat,
});
export const AdminToken = IDL.Text;
export const ShotEvent = IDL.Record({
  'id' : IDL.Nat,
  'multiplier' : IDL.Nat,
  'turnId' : IDL.Nat,
  'target' : IDL.Nat,
  'points' : IDL.Nat,
});
export const Turn = IDL.Record({
  'id' : IDL.Nat,
  'playerId' : IDL.Nat,
  'gameId' : IDL.Nat,
  'score' : IDL.Nat,
  'turnIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPlayer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [Player], []),
  'createGame' : IDL.Func([IDL.Nat], [Game], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Room], []),
  'createShotEvent' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, AdminToken],
      [ShotEvent],
      [],
    ),
  'createTurn' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, AdminToken],
      [Turn],
      [],
    ),
  'getGamesByRoom' : IDL.Func([IDL.Nat], [IDL.Vec(Game)], ['query']),
  'getRoomByCode' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
  'getShotEventsByTurn' : IDL.Func([IDL.Nat], [IDL.Vec(ShotEvent)], ['query']),
  'getTurnsByGameAndIndex' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Turn)],
      ['query'],
    ),
  'health' : IDL.Func([], [IDL.Text], ['query']),
  'updateGameStatus' : IDL.Func(
      [IDL.Nat, GameStatus, IDL.Text, AdminToken],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Nat,
    'joinedAt' : IDL.Nat,
    'isHost' : IDL.Bool,
    'roomId' : IDL.Nat,
  });
  const GameStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : GameStatus,
    'endTime' : IDL.Opt(IDL.Int),
    'roomId' : IDL.Nat,
  });
  const RoomStatus = IDL.Variant({
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'InProgress' : IDL.Null,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'status' : RoomStatus,
    'code' : IDL.Text,
    'adminToken' : IDL.Text,
    'hostId' : IDL.Nat,
  });
  const AdminToken = IDL.Text;
  const ShotEvent = IDL.Record({
    'id' : IDL.Nat,
    'multiplier' : IDL.Nat,
    'turnId' : IDL.Nat,
    'target' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const Turn = IDL.Record({
    'id' : IDL.Nat,
    'playerId' : IDL.Nat,
    'gameId' : IDL.Nat,
    'score' : IDL.Nat,
    'turnIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPlayer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [Player], []),
    'createGame' : IDL.Func([IDL.Nat], [Game], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Room], []),
    'createShotEvent' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, AdminToken],
        [ShotEvent],
        [],
      ),
    'createTurn' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, AdminToken],
        [Turn],
        [],
      ),
    'getGamesByRoom' : IDL.Func([IDL.Nat], [IDL.Vec(Game)], ['query']),
    'getRoomByCode' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
    'getShotEventsByTurn' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ShotEvent)],
        ['query'],
      ),
    'getTurnsByGameAndIndex' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Turn)],
        ['query'],
      ),
    'health' : IDL.Func([], [IDL.Text], ['query']),
    'updateGameStatus' : IDL.Func(
        [IDL.Nat, GameStatus, IDL.Text, AdminToken],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };