/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminToken = string;
export interface Game {
  'id' : bigint,
  'startTime' : bigint,
  'status' : GameStatus,
  'endTime' : [] | [bigint],
  'winnerPlayerId' : [] | [bigint],
  'roomId' : bigint,
}
export type GameStatus = { 'Active' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface GameWithStatistics {
  'avg' : number,
  'win' : boolean,
  'startedAt' : bigint,
  'mode' : string,
  'gameId' : bigint,
  'checkoutPercent' : number,
  'place' : bigint,
  '_180s' : bigint,
  'doubleOut' : boolean,
  'finishedAt' : [] | [bigint],
}
export interface GoogleOAuthConfig {
  'clientId' : string,
  'frontendOAuthRedirectPath' : string,
  'redirectPath' : string,
}
export interface HealthCheck {
  'name' : string,
  'healthy' : boolean,
  'message' : [] | [string],
}
export interface HealthStatus {
  'ok' : boolean,
  'httpCode' : number,
  'components' : Array<HealthCheck>,
  'message' : string,
}
export interface Player {
  'id' : bigint,
  'remainingScore' : bigint,
  'displayName' : string,
  'userId' : [] | [string],
  'joinedAt' : bigint,
  'gameId' : bigint,
  'isHost' : boolean,
  'roomId' : bigint,
}
export interface PlayerGameStats {
  'id' : bigint,
  'userId' : [] | [string],
  'playerId' : bigint,
  'createdAt' : bigint,
  'gameId' : bigint,
  'checkoutAttempts' : bigint,
  'numBusts' : bigint,
  'dartsThrown' : bigint,
  'num180s' : bigint,
  'avg3dart' : number,
  'pointsScoredTotal' : bigint,
  'checkoutSuccess' : bigint,
  'first9Avg' : [] | [number],
}
export interface Room {
  'id' : bigint,
  'status' : RoomStatus,
  'admin_token_hash' : [] | [string],
  'code' : string,
  'owner_user_id' : [] | [Principal],
  'hostId' : string,
}
export type RoomStatus = { 'Open' : null } |
  { 'Closed' : null } |
  { 'InProgress' : null };
export interface ShotEvent {
  'id' : bigint,
  'multiplier' : bigint,
  'turnId' : bigint,
  'target' : bigint,
  'points' : bigint,
}
export type Time = bigint;
export interface Turn {
  'id' : bigint,
  'playerId' : bigint,
  'gameId' : bigint,
  'isBust' : boolean,
  'score' : bigint,
  'turnIndex' : bigint,
  'turnTotal' : bigint,
  'remainingBefore' : bigint,
}
export interface User {
  'id' : string,
  'username' : string,
  'lastLoginAt' : [] | [Time],
  'oauth_subject' : [] | [string],
  'createdAt' : Time,
  'email' : string,
  'email_verified' : boolean,
  'oauth_provider' : [] | [string],
}
export interface UserProfile {
  'username' : string,
  'name' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'gamesPlayed' : bigint,
  'wins' : bigint,
  'total180s' : bigint,
  'checkoutAttempts' : bigint,
  'updatedAt' : bigint,
  'first9AvgOverall' : [] | [number],
  'checkoutSuccess' : bigint,
  'totalBusts' : bigint,
  'winRate' : number,
  'avg3dartOverall' : number,
  'checkoutRate' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<
    [bigint, bigint, string, [] | [string], boolean, [] | [AdminToken]],
    Player
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGame' : ActorMethod<[bigint, [] | [AdminToken]], Game>,
  'createRoomV2' : ActorMethod<
    [string, string, boolean],
    { 'admin_token' : [] | [string], 'room' : Room }
  >,
  'createShotEvent' : ActorMethod<
    [bigint, bigint, bigint, bigint, [] | [AdminToken]],
    ShotEvent
  >,
  'createTurn' : ActorMethod<[bigint, bigint, bigint, [] | [AdminToken]], Turn>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGame' : ActorMethod<[bigint], [] | [Game]>,
  'getGamesByRoom' : ActorMethod<[bigint], Array<Game>>,
  'getGoogleOAuthConfig' : ActorMethod<[], GoogleOAuthConfig>,
  'getGoogleOAuthStartUrl' : ActorMethod<[], string>,
  'getHealthStatus' : ActorMethod<[], HealthStatus>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyStats' : ActorMethod<[], [] | [UserStats]>,
  'getPlayerGameStatsByGame' : ActorMethod<[bigint], Array<PlayerGameStats>>,
  'getPlayerGameStatsByUser' : ActorMethod<[string], Array<PlayerGameStats>>,
  'getPlayersByGame' : ActorMethod<[bigint], Array<Player>>,
  'getRoomByCode' : ActorMethod<[string], [] | [Room]>,
  'getShotEventsByTurn' : ActorMethod<[bigint], Array<ShotEvent>>,
  'getTurnsByGameAndIndex' : ActorMethod<[bigint, bigint], Array<Turn>>,
  'getTurnsByGamePaginated' : ActorMethod<
    [bigint, bigint, bigint],
    Array<Turn>
  >,
  'getUserGamesParticipated' : ActorMethod<
    [string, bigint, bigint, [] | [string], [] | [bigint], [] | [bigint]],
    Array<GameWithStatistics>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[string], [] | [UserStats]>,
  'health' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string], User>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGameWinner' : ActorMethod<[bigint, bigint, [] | [AdminToken]], undefined>,
  'updateGameStatus' : ActorMethod<
    [bigint, GameStatus, [] | [AdminToken]],
    undefined
  >,
  'updatePlayerRemaining' : ActorMethod<
    [bigint, bigint, [] | [AdminToken]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];