/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Game {
  'id' : bigint,
  'startTime' : bigint,
  'status' : GameStatus,
  'endTime' : [] | [bigint],
  'roomId' : bigint,
}
export type GameStatus = { 'Active' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Room {
  'id' : bigint,
  'status' : RoomStatus,
  'code' : string,
  'hostId' : bigint,
}
export type RoomStatus = { 'Open' : null } |
  { 'Closed' : null } |
  { 'InProgress' : null };
export interface Turn {
  'id' : bigint,
  'playerId' : bigint,
  'gameId' : bigint,
  'score' : bigint,
  'turnIndex' : bigint,
}
export interface _SERVICE {
  'createGame' : ActorMethod<[bigint], Game>,
  'createRoom' : ActorMethod<[string, bigint], Room>,
  'createTurn' : ActorMethod<[bigint, bigint, bigint], Turn>,
  'getGamesByRoom' : ActorMethod<[bigint], Array<Game>>,
  'getRoomByCode' : ActorMethod<[string], [] | [Room]>,
  'getTurnsByGameAndIndex' : ActorMethod<[bigint, bigint], Array<Turn>>,
  'health' : ActorMethod<[], string>,
  'updateGameStatus' : ActorMethod<[bigint, GameStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];