/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    remainingScore: bigint;
    displayName: string;
    userId?: string;
    joinedAt: bigint;
    gameId: bigint;
    isHost: boolean;
    roomId: bigint;
}
export interface GameWithStatistics {
    avg: number;
    win: boolean;
    startedAt: bigint;
    mode: string;
    gameId: bigint;
    checkoutPercent: number;
    place: bigint;
    _180s: bigint;
    doubleOut: boolean;
    finishedAt?: bigint;
}
export interface Game {
    id: bigint;
    startTime: bigint;
    status: GameStatus;
    endTime?: bigint;
    winnerPlayerId?: bigint;
    roomId: bigint;
}
export type Time = bigint;
export type AdminToken = string;
export interface User {
    id: string;
    username: string;
    lastLoginAt?: Time;
    oauth_subject?: string;
    createdAt: Time;
    email: string;
    email_verified: boolean;
    oauth_provider?: string;
}
export interface Room {
    id: bigint;
    status: RoomStatus;
    admin_token_hash?: string;
    code: string;
    owner_user_id?: Principal;
    hostId: string;
}
export interface HealthCheck {
    name: string;
    healthy: boolean;
    message?: string;
}
export interface GoogleOAuthConfig {
    clientId: string;
    frontendOAuthRedirectPath: string;
    redirectPath: string;
}
export interface HealthStatus {
    ok: boolean;
    httpCode: number;
    components: Array<HealthCheck>;
    message: string;
}
export interface PlayerGameStats {
    id: bigint;
    userId?: string;
    playerId: bigint;
    createdAt: bigint;
    gameId: bigint;
    checkoutAttempts: bigint;
    numBusts: bigint;
    dartsThrown: bigint;
    num180s: bigint;
    avg3dart: number;
    pointsScoredTotal: bigint;
    checkoutSuccess: bigint;
    first9Avg?: number;
}
export interface ShotEvent {
    id: bigint;
    multiplier: bigint;
    turnId: bigint;
    target: bigint;
    points: bigint;
}
export interface Turn {
    id: bigint;
    playerId: bigint;
    gameId: bigint;
    isBust: boolean;
    score: bigint;
    turnIndex: bigint;
    turnTotal: bigint;
    remainingBefore: bigint;
}
export interface UserStats {
    gamesPlayed: bigint;
    wins: bigint;
    total180s: bigint;
    checkoutAttempts: bigint;
    updatedAt: bigint;
    first9AvgOverall?: number;
    checkoutSuccess: bigint;
    totalBusts: bigint;
    winRate: number;
    avg3dartOverall: number;
    checkoutRate: number;
}
export interface UserProfile {
    username: string;
    name: string;
    email: string;
}
export enum GameStatus {
    Active = "Active",
    Completed = "Completed",
    Pending = "Pending"
}
export enum RoomStatus {
    Open = "Open",
    Closed = "Closed",
    InProgress = "InProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPlayer(gameId: bigint, roomId: bigint, displayName: string, userId: string | null, isHost: boolean, adminToken: AdminToken | null): Promise<Player>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createGame(roomId: bigint, adminToken: AdminToken | null): Promise<Game>;
    createRoomV2(code: string, hostId: string, create_with_account: boolean): Promise<{
        admin_token?: string;
        room: Room;
    }>;
    createShotEvent(turnId: bigint, target: bigint, points: bigint, multiplier: bigint, adminToken: AdminToken | null): Promise<ShotEvent>;
    createTurn(gameId: bigint, playerId: bigint, turnIndex: bigint, adminToken: AdminToken | null): Promise<Turn>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGame(gameId: bigint): Promise<Game | null>;
    getGamesByRoom(roomId: bigint): Promise<Array<Game>>;
    getGoogleOAuthConfig(): Promise<GoogleOAuthConfig>;
    getGoogleOAuthStartUrl(): Promise<string>;
    getHealthStatus(): Promise<HealthStatus>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyStats(): Promise<UserStats | null>;
    getPlayerGameStatsByGame(gameId: bigint): Promise<Array<PlayerGameStats>>;
    getPlayerGameStatsByUser(userId: string): Promise<Array<PlayerGameStats>>;
    getPlayersByGame(gameId: bigint): Promise<Array<Player>>;
    getRoomByCode(code: string): Promise<Room | null>;
    getShotEventsByTurn(turnId: bigint): Promise<Array<ShotEvent>>;
    getTurnsByGameAndIndex(gameId: bigint, turnIndex: bigint): Promise<Array<Turn>>;
    getTurnsByGamePaginated(gameId: bigint, limit: bigint, offset: bigint): Promise<Array<Turn>>;
    getUserGamesParticipated(userId: string, limit: bigint, offset: bigint, mode: string | null, from: bigint | null, to: bigint | null): Promise<Array<GameWithStatistics>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStats(userId: string): Promise<UserStats | null>;
    health(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    register(email: string, username: string): Promise<User>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setGameWinner(gameId: bigint, playerId: bigint, adminToken: AdminToken | null): Promise<void>;
    updateGameStatus(gameId: bigint, newStatus: GameStatus, adminToken: AdminToken | null): Promise<void>;
    updatePlayerRemaining(playerId: bigint, newRemaining: bigint, adminToken: AdminToken | null): Promise<void>;
}
import type { AdminToken as _AdminToken, Game as _Game, GameStatus as _GameStatus, GameWithStatistics as _GameWithStatistics, HealthCheck as _HealthCheck, HealthStatus as _HealthStatus, Player as _Player, PlayerGameStats as _PlayerGameStats, Room as _Room, RoomStatus as _RoomStatus, Time as _Time, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UserStats as _UserStats } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPlayer(arg0: bigint, arg1: bigint, arg2: string, arg3: string | null, arg4: boolean, arg5: AdminToken | null): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Player_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGame(arg0: bigint, arg1: AdminToken | null): Promise<Game> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(arg0, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Game_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(arg0, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Game_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRoomV2(arg0: string, arg1: string, arg2: boolean): Promise<{
        admin_token?: string;
        room: Room;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoomV2(arg0, arg1, arg2);
                return from_candid_record_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoomV2(arg0, arg1, arg2);
            return from_candid_record_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createShotEvent(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: AdminToken | null): Promise<ShotEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.createShotEvent(arg0, arg1, arg2, arg3, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShotEvent(arg0, arg1, arg2, arg3, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createTurn(arg0: bigint, arg1: bigint, arg2: bigint, arg3: AdminToken | null): Promise<Turn> {
        if (this.processError) {
            try {
                const result = await this.actor.createTurn(arg0, arg1, arg2, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTurn(arg0, arg1, arg2, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(arg0: bigint): Promise<Game | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGamesByRoom(arg0: bigint): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGamesByRoom(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGamesByRoom(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoogleOAuthConfig(): Promise<GoogleOAuthConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoogleOAuthConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoogleOAuthConfig();
            return result;
        }
    }
    async getGoogleOAuthStartUrl(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoogleOAuthStartUrl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoogleOAuthStartUrl();
            return result;
        }
    }
    async getHealthStatus(): Promise<HealthStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthStatus();
                return from_candid_HealthStatus_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthStatus();
            return from_candid_HealthStatus_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyStats(): Promise<UserStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerGameStatsByGame(arg0: bigint): Promise<Array<PlayerGameStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerGameStatsByGame(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerGameStatsByGame(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerGameStatsByUser(arg0: string): Promise<Array<PlayerGameStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerGameStatsByUser(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerGameStatsByUser(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByGame(arg0: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByGame(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByGame(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomByCode(arg0: string): Promise<Room | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomByCode(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomByCode(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShotEventsByTurn(arg0: bigint): Promise<Array<ShotEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShotEventsByTurn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShotEventsByTurn(arg0);
            return result;
        }
    }
    async getTurnsByGameAndIndex(arg0: bigint, arg1: bigint): Promise<Array<Turn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTurnsByGameAndIndex(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTurnsByGameAndIndex(arg0, arg1);
            return result;
        }
    }
    async getTurnsByGamePaginated(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<Turn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTurnsByGamePaginated(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTurnsByGamePaginated(arg0, arg1, arg2);
            return result;
        }
    }
    async getUserGamesParticipated(arg0: string, arg1: bigint, arg2: bigint, arg3: string | null, arg4: bigint | null, arg5: bigint | null): Promise<Array<GameWithStatistics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserGamesParticipated(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserGamesParticipated(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(arg0: string): Promise<UserStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async health(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.health();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.health();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_User_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_User_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setGameWinner(arg0: bigint, arg1: bigint, arg2: AdminToken | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGameWinner(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGameWinner(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateGameStatus(arg0: bigint, arg1: GameStatus, arg2: AdminToken | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGameStatus(arg0, to_candid_GameStatus_n46(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGameStatus(arg0, to_candid_GameStatus_n46(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePlayerRemaining(arg0: bigint, arg1: bigint, arg2: AdminToken | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerRemaining(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerRemaining(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_GameStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_GameWithStatistics_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameWithStatistics): GameWithStatistics {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_HealthCheck_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthCheck): HealthCheck {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_HealthStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerGameStats_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerGameStats): PlayerGameStats {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RoomStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomStatus): RoomStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserStats_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStats): UserStats {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_User_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Game]): Game | null {
    return value.length === 0 ? null : from_candid_Game_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserStats]): UserStats | null {
    return value.length === 0 ? null : from_candid_UserStats_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Room]): Room | null {
    return value.length === 0 ? null : from_candid_Room_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin_token: [] | [string];
    room: _Room;
}): {
    admin_token?: string;
    room: Room;
} {
    return {
        admin_token: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.admin_token)),
        room: from_candid_Room_n15(_uploadFile, _downloadFile, value.room)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RoomStatus;
    admin_token_hash: [] | [string];
    code: string;
    owner_user_id: [] | [Principal];
    hostId: string;
}): {
    id: bigint;
    status: RoomStatus;
    admin_token_hash?: string;
    code: string;
    owner_user_id?: Principal;
    hostId: string;
} {
    return {
        id: value.id,
        status: from_candid_RoomStatus_n17(_uploadFile, _downloadFile, value.status),
        admin_token_hash: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.admin_token_hash)),
        code: value.code,
        owner_user_id: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.owner_user_id)),
        hostId: value.hostId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    httpCode: number;
    components: Array<_HealthCheck>;
    message: string;
}): {
    ok: boolean;
    httpCode: number;
    components: Array<HealthCheck>;
    message: string;
} {
    return {
        ok: value.ok,
        httpCode: value.httpCode,
        components: from_candid_vec_n27(_uploadFile, _downloadFile, value.components),
        message: value.message
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    healthy: boolean;
    message: [] | [string];
}): {
    name: string;
    healthy: boolean;
    message?: string;
} {
    return {
        name: value.name,
        healthy: value.healthy,
        message: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.message))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gamesPlayed: bigint;
    wins: bigint;
    total180s: bigint;
    checkoutAttempts: bigint;
    updatedAt: bigint;
    first9AvgOverall: [] | [number];
    checkoutSuccess: bigint;
    totalBusts: bigint;
    winRate: number;
    avg3dartOverall: number;
    checkoutRate: number;
}): {
    gamesPlayed: bigint;
    wins: bigint;
    total180s: bigint;
    checkoutAttempts: bigint;
    updatedAt: bigint;
    first9AvgOverall?: number;
    checkoutSuccess: bigint;
    totalBusts: bigint;
    winRate: number;
    avg3dartOverall: number;
    checkoutRate: number;
} {
    return {
        gamesPlayed: value.gamesPlayed,
        wins: value.wins,
        total180s: value.total180s,
        checkoutAttempts: value.checkoutAttempts,
        updatedAt: value.updatedAt,
        first9AvgOverall: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.first9AvgOverall)),
        checkoutSuccess: value.checkoutSuccess,
        totalBusts: value.totalBusts,
        winRate: value.winRate,
        avg3dartOverall: value.avg3dartOverall,
        checkoutRate: value.checkoutRate
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: [] | [string];
    playerId: bigint;
    createdAt: bigint;
    gameId: bigint;
    checkoutAttempts: bigint;
    numBusts: bigint;
    dartsThrown: bigint;
    num180s: bigint;
    avg3dart: number;
    pointsScoredTotal: bigint;
    checkoutSuccess: bigint;
    first9Avg: [] | [number];
}): {
    id: bigint;
    userId?: string;
    playerId: bigint;
    createdAt: bigint;
    gameId: bigint;
    checkoutAttempts: bigint;
    numBusts: bigint;
    dartsThrown: bigint;
    num180s: bigint;
    avg3dart: number;
    pointsScoredTotal: bigint;
    checkoutSuccess: bigint;
    first9Avg?: number;
} {
    return {
        id: value.id,
        userId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.userId)),
        playerId: value.playerId,
        createdAt: value.createdAt,
        gameId: value.gameId,
        checkoutAttempts: value.checkoutAttempts,
        numBusts: value.numBusts,
        dartsThrown: value.dartsThrown,
        num180s: value.num180s,
        avg3dart: value.avg3dart,
        pointsScoredTotal: value.pointsScoredTotal,
        checkoutSuccess: value.checkoutSuccess,
        first9Avg: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.first9Avg))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    remainingScore: bigint;
    displayName: string;
    userId: [] | [string];
    joinedAt: bigint;
    gameId: bigint;
    isHost: boolean;
    roomId: bigint;
}): {
    id: bigint;
    remainingScore: bigint;
    displayName: string;
    userId?: string;
    joinedAt: bigint;
    gameId: bigint;
    isHost: boolean;
    roomId: bigint;
} {
    return {
        id: value.id,
        remainingScore: value.remainingScore,
        displayName: value.displayName,
        userId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.userId)),
        joinedAt: value.joinedAt,
        gameId: value.gameId,
        isHost: value.isHost,
        roomId: value.roomId
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    avg: number;
    win: boolean;
    startedAt: bigint;
    mode: string;
    gameId: bigint;
    checkoutPercent: number;
    place: bigint;
    _180s: bigint;
    doubleOut: boolean;
    finishedAt: [] | [bigint];
}): {
    avg: number;
    win: boolean;
    startedAt: bigint;
    mode: string;
    gameId: bigint;
    checkoutPercent: number;
    place: bigint;
    _180s: bigint;
    doubleOut: boolean;
    finishedAt?: bigint;
} {
    return {
        avg: value.avg,
        win: value.win,
        startedAt: value.startedAt,
        mode: value.mode,
        gameId: value.gameId,
        checkoutPercent: value.checkoutPercent,
        place: value.place,
        _180s: value._180s,
        doubleOut: value.doubleOut,
        finishedAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.finishedAt))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    username: string;
    lastLoginAt: [] | [_Time];
    oauth_subject: [] | [string];
    createdAt: _Time;
    email: string;
    email_verified: boolean;
    oauth_provider: [] | [string];
}): {
    id: string;
    username: string;
    lastLoginAt?: Time;
    oauth_subject?: string;
    createdAt: Time;
    email: string;
    email_verified: boolean;
    oauth_provider?: string;
} {
    return {
        id: value.id,
        username: value.username,
        lastLoginAt: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.lastLoginAt)),
        oauth_subject: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.oauth_subject)),
        createdAt: value.createdAt,
        email: value.email,
        email_verified: value.email_verified,
        oauth_provider: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.oauth_provider))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _GameStatus;
    endTime: [] | [bigint];
    winnerPlayerId: [] | [bigint];
    roomId: bigint;
}): {
    id: bigint;
    startTime: bigint;
    status: GameStatus;
    endTime?: bigint;
    winnerPlayerId?: bigint;
    roomId: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_GameStatus_n10(_uploadFile, _downloadFile, value.status),
        endTime: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.endTime)),
        winnerPlayerId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.winnerPlayerId)),
        roomId: value.roomId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): GameStatus {
    return "Active" in value ? GameStatus.Active : "Completed" in value ? GameStatus.Completed : "Pending" in value ? GameStatus.Pending : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
} | {
    InProgress: null;
}): RoomStatus {
    return "Open" in value ? RoomStatus.Open : "Closed" in value ? RoomStatus.Closed : "InProgress" in value ? RoomStatus.InProgress : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthCheck>): Array<HealthCheck> {
    return value.map((x)=>from_candid_HealthCheck_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerGameStats>): Array<PlayerGameStats> {
    return value.map((x)=>from_candid_PlayerGameStats_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameWithStatistics>): Array<GameWithStatistics> {
    return value.map((x)=>from_candid_GameWithStatistics_n41(_uploadFile, _downloadFile, x));
}
function to_candid_GameStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): _GameStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminToken | null): [] | [_AdminToken] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): {
    Active: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == GameStatus.Active ? {
        Active: null
    } : value == GameStatus.Completed ? {
        Completed: null
    } : value == GameStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
