/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    userId: bigint;
    joinedAt: bigint;
    isHost: boolean;
    roomId: bigint;
}
export interface Game {
    id: bigint;
    startTime: bigint;
    status: GameStatus;
    endTime?: bigint;
    roomId: bigint;
}
export interface ShotEvent {
    id: bigint;
    multiplier: bigint;
    turnId: bigint;
    target: bigint;
    points: bigint;
}
export interface Turn {
    id: bigint;
    playerId: bigint;
    gameId: bigint;
    score: bigint;
    turnIndex: bigint;
}
export interface Room {
    id: bigint;
    status: RoomStatus;
    code: string;
    adminToken: string;
    hostId: bigint;
}
export type AdminToken = string;
export enum GameStatus {
    Active = "Active",
    Completed = "Completed",
    Pending = "Pending"
}
export enum RoomStatus {
    Open = "Open",
    Closed = "Closed",
    InProgress = "InProgress"
}
export interface backendInterface {
    addPlayer(userId: bigint, roomId: bigint, isHost: boolean): Promise<Player>;
    createGame(roomId: bigint): Promise<Game>;
    createRoom(code: string, hostId: bigint, adminToken: string): Promise<Room>;
    createShotEvent(turnId: bigint, target: bigint, points: bigint, multiplier: bigint, roomCode: string, adminToken: AdminToken): Promise<ShotEvent>;
    createTurn(gameId: bigint, playerId: bigint, turnIndex: bigint, roomCode: string, adminToken: AdminToken): Promise<Turn>;
    getGamesByRoom(roomId: bigint): Promise<Array<Game>>;
    getRoomByCode(code: string): Promise<Room | null>;
    getShotEventsByTurn(turnId: bigint): Promise<Array<ShotEvent>>;
    getTurnsByGameAndIndex(gameId: bigint, turnIndex: bigint): Promise<Array<Turn>>;
    health(): Promise<string>;
    updateGameStatus(gameId: bigint, newStatus: GameStatus, roomCode: string, adminToken: AdminToken): Promise<void>;
}
import type { Game as _Game, GameStatus as _GameStatus, Room as _Room, RoomStatus as _RoomStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPlayer(arg0: bigint, arg1: bigint, arg2: boolean): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2);
            return result;
        }
    }
    async createGame(arg0: bigint): Promise<Game> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(arg0);
                return from_candid_Game_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(arg0);
            return from_candid_Game_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRoom(arg0: string, arg1: bigint, arg2: string): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0, arg1, arg2);
                return from_candid_Room_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0, arg1, arg2);
            return from_candid_Room_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createShotEvent(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string, arg5: AdminToken): Promise<ShotEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.createShotEvent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShotEvent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createTurn(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: AdminToken): Promise<Turn> {
        if (this.processError) {
            try {
                const result = await this.actor.createTurn(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTurn(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getGamesByRoom(arg0: bigint): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGamesByRoom(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGamesByRoom(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomByCode(arg0: string): Promise<Room | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomByCode(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomByCode(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShotEventsByTurn(arg0: bigint): Promise<Array<ShotEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShotEventsByTurn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShotEventsByTurn(arg0);
            return result;
        }
    }
    async getTurnsByGameAndIndex(arg0: bigint, arg1: bigint): Promise<Array<Turn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTurnsByGameAndIndex(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTurnsByGameAndIndex(arg0, arg1);
            return result;
        }
    }
    async health(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.health();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.health();
            return result;
        }
    }
    async updateGameStatus(arg0: bigint, arg1: GameStatus, arg2: string, arg3: AdminToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGameStatus(arg0, to_candid_GameStatus_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGameStatus(arg0, to_candid_GameStatus_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
}
function from_candid_GameStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_RoomStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomStatus): RoomStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Room]): Room | null {
    return value.length === 0 ? null : from_candid_Room_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _GameStatus;
    endTime: [] | [bigint];
    roomId: bigint;
}): {
    id: bigint;
    startTime: bigint;
    status: GameStatus;
    endTime?: bigint;
    roomId: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_GameStatus_n3(_uploadFile, _downloadFile, value.status),
        endTime: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endTime)),
        roomId: value.roomId
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RoomStatus;
    code: string;
    adminToken: string;
    hostId: bigint;
}): {
    id: bigint;
    status: RoomStatus;
    code: string;
    adminToken: string;
    hostId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RoomStatus_n8(_uploadFile, _downloadFile, value.status),
        code: value.code,
        adminToken: value.adminToken,
        hostId: value.hostId
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): GameStatus {
    return "Active" in value ? GameStatus.Active : "Completed" in value ? GameStatus.Completed : "Pending" in value ? GameStatus.Pending : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
} | {
    InProgress: null;
}): RoomStatus {
    return "Open" in value ? RoomStatus.Open : "Closed" in value ? RoomStatus.Closed : "InProgress" in value ? RoomStatus.InProgress : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n1(_uploadFile, _downloadFile, x));
}
function to_candid_GameStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): _GameStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameStatus): {
    Active: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == GameStatus.Active ? {
        Active: null
    } : value == GameStatus.Completed ? {
        Completed: null
    } : value == GameStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
